spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 12801

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12701/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug